### ISSUE TITLE
Memory leak found in event handler function

### ISSUE THREAD

**Issue by jalpanparekh** [nopnop2002/esp-idf-mqtt-broker#35]
Hi,

We have found memory leak in Event Handler Function **fn()** in **mqtt_server.c**. Where **mg_strdup**() function allocate memory and didn't release it for **sub->topic.ptr**.

Can you please confirm once if I misunderstood.

Thanks,
Jalpan Parekh

**Comment by nopnop2002** [comment]
Thank you for reporting.

I also check.

**Comment by nopnop2002** [comment]
I fixed a memory leak in the latest version.

**Comment by jalpanparekh** [comment]
Thanks for the quick reply. I will check your latest patch.
