### ISSUE TITLE
Bug inside README installation instruction

### ISSUE THREAD

**Issue by chepil** [nopnop2002/esp-idf-mqtt-broker#39]
please fix readme

incorrect string:
echo "idf_component_register(SRCS \"mongoose.c\" PRIV_REQUIRES esp_timer INCLUDE_DIRS \".\") > CMakeLists.txt

fix string:
echo "idf_component_register(SRCS \"mongoose.c\" PRIV_REQUIRES esp_timer INCLUDE_DIRS \".\")" > CMakeLists.txt

need double quote at the end of line...

**Comment by nopnop2002** [comment]
Thank you for reporting.

I Fixed.
