### ISSUE TITLE
The latest mongoose is incompatible

### ISSUE THREAD

**Issue by mvdw** [nopnop2002/esp-idf-mqtt-broker#40]
The installation instructions say:
`git clone https://github.com/cesanta/mongoose.git`
But this does not work. 
The following does work:
`git clone -b 7.6 https://github.com/cesanta/mongoose.git`

BTW: I guess it is not related, but I used this:
`git clone -b v4.4.2 --recursive https://github.com/espressif/esp-idf.git`

**Comment by nopnop2002** [comment]
Thank you for your report.
I revised the README.
I confirmed that it works with mongoose Version 7.7.

I'm using the ESP-IDF below.
```
$ idf.py --version
ESP-IDF v5.0-dev-4037-g9b8c558e63-dirty
```
