### ISSUE TITLE
Using esp-idf-mqtt broker as a library

### ISSUE THREAD

**Issue by ghost** [nopnop2002/esp-idf-mqtt-broker#46]
I have an ESP-IDF application, already connected to the WiFi.
I want to receive data from a couple of MQTT devices. 

Can I use this code as a library? Just to add the broker functionality to my application, so the devices can publish topics and I can catch them?

**Comment by nopnop2002** [comment]
This is an MQTT Broker.
A sample of MQTT Client can be found here.

https://github.com/espressif/esp-idf/tree/master/examples/protocols/mqtt/tcp
