### ISSUE TITLE
What is the use of FAT file system in this project?

### ISSUE THREAD

**Issue by Bosemani** [nopnop2002/esp-idf-mqtt-broker#48]
Hai @nopnop2002 ,
    First, I'm appreciating your work. 
I'm having doubt, in your code main I found this part
`	// Initializing FAT file system 

	char *partition_label = "storage";
	wl_handle_t s_wl_handle = mountFATFS(partition_label, MOUNT_POINT);
	if (s_wl_handle < 0) {
		ESP_LOGE(TAG, "mountFATFS fail");
		while(1) { vTaskDelay(1); }
	}`

Why we need this storage partition?

Best Regards
Bose

**Comment by nopnop2002** [comment]
As you pointed out, this is completely unnecessary code.

```
char *partition_label = "storage";
wl_handle_t s_wl_handle = mountFATFS(partition_label, MOUNT_POINT);
if (s_wl_handle < 0) {
	ESP_LOGE(TAG, "mountFATFS fail");
	while(1) { vTaskDelay(1); }
}`
```

I never noticed it until now.

Initializing storage partitions is not required for this project.

I removed unused code.

Thank you for your report.

**Comment by Bosemani** [comment]
Thank you for conformation.
