### ISSUE TITLE
Bridge local MQTT broker and cloud MQTT Broker

### ISSUE THREAD

**Issue by Bosemani** [nopnop2002/esp-idf-mqtt-broker#50]
Hai @nopnop2002 
       I'm having a ESP32 running broker locally, also I'm having one Cloud MQTT broker. 
Is it possible to bridge two MQTT brokers. You can find in Mosquitto brokers ([Link](http://www.steves-internet-guide.com/mosquitto-bridge-configuration/)).

Regards
Bose

**Comment by nopnop2002** [comment]
Unfortunately it does not have such functionality.

**Comment by Bosemani** [comment]
@nopnop2002 Thank you. 
I will close this.
